version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-test-invex
    environment:
      MYSQL_DATABASE: test_invex
      MYSQL_ROOT_PASSWORD: test1nvex
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - invex_network
    healthcheck: # <--- Añade un healthcheck a la DB para mejor gestión
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 3s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-app
    ports:
      - "8881:8881"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db: 
        condition: service_healthy 
    networks:
      - invex_network
    restart: on-failure
    volumes:
       - ../logs/service-employee:/var/log/service-employee
    command: > # <--- Añade un comando que espera por la DB antes de iniciar la app
      bash -c "while ! mysqladmin ping -hdb --silent; do
        echo waiting for db;
        sleep 15;
      done;
      java -jar app.jar"

volumes:
  db_data:

networks:
  invex_network:
    driver: bridge